package com.learnwebservices.services.tempconverter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-11-08T13:24:02.793+01:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://learnwebservices.com/services/tempconverter", name = "TempConverterEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TempConverterEndpoint {

    @WebMethod(operationName = "CelsiusToFahrenheit")
    @WebResult(name = "CelsiusToFahrenheitResponse", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "CelsiusToFahrenheitResponse")
    public CelsiusToFahrenheitResponse celsiusToFahrenheit(

        @WebParam(partName = "CelsiusToFahrenheitRequest", name = "CelsiusToFahrenheitRequest", targetNamespace = "http://learnwebservices.com/services/tempconverter")
        CelsiusToFahrenheitRequest celsiusToFahrenheitRequest
    );

    @WebMethod(operationName = "FahrenheitToCelsius")
    @WebResult(name = "FahrenheitToCelsiusResponse", targetNamespace = "http://learnwebservices.com/services/tempconverter", partName = "FahrenheitToCelsiusResponse")
    public FahrenheitToCelsiusResponse fahrenheitToCelsius(

        @WebParam(partName = "FahrenheitToCelsiusRequest", name = "FahrenheitToCelsiusRequest", targetNamespace = "http://learnwebservices.com/services/tempconverter")
        FahrenheitToCelsiusRequest fahrenheitToCelsiusRequest
    );
}
